apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yml: |
    tunnel: 58c2d850-c1d3-4c31-8954-864c772e37de
    credentials-file: /etc/cloudflared/58c2d850-c1d3-4c31-8954-864c772e37de.json

    ingress:
      - hostname: drone.namth.online
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: threads.namth.online
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: threads-api.namth.online
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
        originRequest:
          http2Origin: true          
          connectTimeout: 30s
          tcpKeepAlive: 30s
      - hostname: minio-api.namth.online
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: minio.namth.online
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: argocd.namth.online
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
        originRequest:
          noTLSVerify: true
      - hostname: kibana.namth.online
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: grafana.namth.online
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: haohan.namth.online
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - service: http_status:404
